name: "ğŸš€ npm release"

on:
    push:
        branches:
            - master

jobs:
    release:
        name: ğŸš€ release
        runs-on: ubuntu-latest
        environment: npm
        steps:
            - name: ğŸ“š checkout
              uses: actions/checkout@v3
            - name: Set up Git user
              run: |
                git config --global user.email "sjpdkedkdjkdkdjdmddd@gmail.com"
                git config --global user.name "trysquaddf"
            - name: ğŸŸ¢ node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: ğŸš§ install dependencies
              run: npm ci
            - name: Update package version
              run: npm version patch
              working-directory: .
            - name: ğŸ­ build
              run: npm run build
            - name: ğŸš€ publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
